# ./Taskfile.yaml
# See: https://taskfile.dev/api/  

version: "3"  

tasks:  
  default: # Если не указать конкретную команду, будут выполнены дефолтные
    cmds:  
      - task: generate  
      - task: run
  generate:  ## Команда для генерации
    aliases: ## Алиасы команды, для простоты использования
      - gen  
    desc: "Generate code from proto files"  
    cmds:  ## Тут описываем необходимые bash-команды
      - protoc --go_out=./api/grpc/gen ./api/grpc/proto/*.proto --go-grpc_out=./api/grpc/gen ./api/grpc/proto/*.proto
  run: 
    desc: "start app"
    cmds: 
      - go run ./api/cmd/main.go --config=./api/config/local.yaml